### ISSUE TITLE
Upgrade references to the general text modules

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Pediatric_Qualification_Package_CYP2C8_Ontogeny#11]
Replace all refs to the general text modules with tag **v1.1**, e.g.
https://raw.githubusercontent.com/Open-Systems-Pharmacology/Qualification-text-modules/v1.1/OSPS_Introduction.md

**Comment by Incei** [comment]
We could this of using general text modules for pediatrics too, however the references should not be copied over in to a references section...
